name: Build and Release VSCode Extension

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    name: Build, Version Bump, and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Bump Version
        id: version_bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"1
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
          echo "new_version=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Build VSIX Package
        run: vsce package --out arm-syntax-vscode-extension-${{ env.new_version }}.vsix
        
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Build VSIX Package
        run: vsce package --out arm-syntax-vscode-extension-${{ env.new_version }}.vsix

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: arm-syntax-vscode-extension-${{ env.new_version }}.vsix
          tag: v${{ env.new_version }}
          name: "Release v${{ env.new_version }}"
          body: "Automated release of version v${{ env.new_version }}"
          allowUpdates: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
